############################
# Route traffic monitoring #
############################

- name: API Route Monitoring
  become: false
  hosts: localhost
  gather_facts: false
  tasks:
    - debug:
        msg: “Starting Route Monitoring API call”


# Get current configuration settings to establish baseline for changes.

    - name: Collect current configuration settings
      uri:
        url: https://pt3proxy.devapi.tradedesk.co.za/api/v1/PTSettings
        method: GET
      register: results
    - debug:
        var: results.json.values