# Velocity Trade
# Network Debug Script Version: 1
# First Release Date: 2022-09-09
# Last Modified Date: 2022-09-15
# Author: Wikus Du Plessis
# Description: Run network debug tests on the remote server and retrieve logs, enable sharing of network debugging information with third parties.

# Ansible Playbook
- name: Ansible_Playbook_Test
  hosts: all
  tasks:

# Start the tcpdump service with filter in an async state. The dump will run in the background while we do other high-level network traffic tests.
    - name: start_tcpdump
      async: '{{duration}}'
      poll: 0
      command: sudo tcpdump -w {{cap_file}} host {{destination_ip}}
      register: async_tcpdump

# Run a stock standard ICMP ping
    - name: start_ping 
      command: sudo ping {{destination_ip}} -c {{count}} -D
      register: ping_result


# Logical pause to wait for the tcpdump utility to finish before consolidating logs.
    - name: tcpdump_sync_timeout
      ansible.builtin.async_status:
        jid: '{{ async_tcpdump.ansible_job_id }}'
      register: job_result
      until: job_result.finished
      retries: 10
      delay: 10