# Velocity Trade
# Network Debug Script Version: 1
# First Release Date: 2022-09-09
# Last Modified Date: 2022-09-15
# Author: Wikus Du Plessis
# Description: Run network debug tests on the remote server and retrieve logs, enable sharing of network debugging information with third parties.

# Ansible Playbook
- name: Ansible_Playbook_Test
  hosts: all
  tasks:

# Start the tcpdump service with filter in an async state. The dump will run in the background while we do other high-level network traffic tests.
    - name: start_tcpdump
      async: '{{duration}}'
      poll: 0
      command: sudo tcpdump -G {{duration}} -W 1 -w {{cap_file}}.pcap host {{destination_ip}}
      register: async_tcpdump

# Run a stock standard ICMP ping
    - name: start_ping 
      command: sudo ping {{destination_ip}} -c {{count}} -D
      register: ping_result

# Run My Trace Route utility on specify port/ip/count & protocol.
    - name: start_mtr 
      command: sudo mtr {{destination_ip}} -C {{count}} --{{protocol}} --report

# Check if remote port is open and currently in an active listening state. Similiar to the telnet port check.
    - name: start_telnet
      command: ( sudo timeout 5 bash -c '</dev/tcp/{{destination_ip}}/{{destination_port}} && echo PORT OPEN || echo PORT CLOSED') 2>/dev/null

  
# ///TODO/// 
# 1) Send email with attached log files to specified email addresses. Will require SMTP authentication.
# 2) Add additional troubleshooting tools to expand the scope of debug to disks, CPU and Memory consumption. Alternatively, create seperate jobs consisting of the following.
#    Can be consolidated into a single work-flow for modular deployment and execution.